{
 "title": "Micronaut Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "The uptime of the Java virtual machine",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "A - The \"recent cpu usage\" of the system the application is running in\nB - The \"recent cpu usage\" for the Java Virtual Machine process",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "description": "The amount of used memory",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Purchases",
   "type": "timeseries",
   "description": "Total number of new purchases",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "purchase_total{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } }
 ]
}